Error | notauth:: | 20/05/2019 10:38:26:3826 | 12 | com.cpp.calypso.framework.ManejadorExcepciones | Excepcion: | HandleAbpExceptionEventHandler.HandleEvent => ManejadorExcepciones.HandleException => NLogLogger.Error | An error occurred while updating the entries. See the inner exception for details. | !
Error | notauth:: | 20/05/2019 10:46:43:4643 | 52 | com.cpp.calypso.framework.ManejadorExcepciones | Excepcion: | HandleAbpExceptionEventHandler.HandleEvent => ManejadorExcepciones.HandleException => NLogLogger.Error | An error occurred while updating the entries. See the inner exception for details. | !
Error | notauth:: | 20/05/2019 11:08:41:841 | 12 | com.cpp.calypso.framework.ManejadorExcepciones | Excepcion: | HandleAbpExceptionEventHandler.HandleEvent => ManejadorExcepciones.HandleException => NLogLogger.Error | An error occurred while updating the entries. See the inner exception for details. | !
Error | notauth:: | 20/05/2019 16:19:13:1913 | 151 | com.cpp.calypso.framework.ManejadorExcepciones | Excepcion: | HandleAbpExceptionEventHandler.HandleEvent => ManejadorExcepciones.HandleException => NLogLogger.Error | An error occurred while updating the entries. See the inner exception for details. | !
Error | notauth:: | 20/05/2019 16:20:25:2025 | 148 | com.cpp.calypso.framework.ManejadorExcepciones | Excepcion: | HandleAbpExceptionEventHandler.HandleEvent => ManejadorExcepciones.HandleException => NLogLogger.Error | An error occurred while updating the entries. See the inner exception for details. | !
Error | notauth:: | 20/05/2019 16:23:07:237 | 9 | com.cpp.calypso.framework.ManejadorExcepciones | Excepcion: | HandleAbpExceptionEventHandler.HandleEvent => ManejadorExcepciones.HandleException => NLogLogger.Error | An error occurred while updating the entries. See the inner exception for details. | !
Error | notauth:: | 20/05/2019 16:35:02:352 | 10 | com.cpp.calypso.framework.ManejadorExcepciones | Excepcion: | HandleAbpExceptionEventHandler.HandleEvent => ManejadorExcepciones.HandleException => NLogLogger.Error | An error occurred while updating the entries. See the inner exception for details. | !
Error | notauth:: | 20/05/2019 16:52:10:5210 | 12 | com.cpp.calypso.framework.ManejadorExcepciones | Excepcion: | HandleAbpExceptionEventHandler.HandleEvent => ManejadorExcepciones.HandleException => NLogLogger.Error | An error occurred while updating the entries. See the inner exception for details. | !
Error | notauth:: | 20/05/2019 16:56:49:5649 | 19 | com.cpp.calypso.framework.ManejadorExcepciones | Excepcion: | HandleAbpExceptionEventHandler.HandleEvent => ManejadorExcepciones.HandleException => NLogLogger.Error | An error occurred while updating the entries. See the inner exception for details. | !
Error | notauth:: | 20/05/2019 17:03:16:316 | 12 | com.cpp.calypso.framework.ManejadorExcepciones | Excepcion: | HandleAbpExceptionEventHandler.HandleEvent => ManejadorExcepciones.HandleException => NLogLogger.Error | An error occurred while updating the entries. See the inner exception for details. | !
Error | notauth:: | 20/05/2019 17:03:17:317 | 12 | com.cpp.calypso.framework.ManejadorExcepciones | Excepcion: | HandleAbpExceptionEventHandler.HandleEvent => ManejadorExcepciones.HandleException => NLogLogger.Error | An error occurred while updating the entries. See the inner exception for details. | !
