Error | notauth:: | 04/07/2019 11:47:52:4752 | 23 | com.cpp.calypso.framework.ManejadorExcepciones | Excepcion: | HandleAbpExceptionEventHandler.HandleEvent => ManejadorExcepciones.HandleException => NLogLogger.Error | An error occurred while updating the entries. See the inner exception for details. | !
Error | notauth:: | 04/07/2019 11:48:19:4819 | 23 | com.cpp.calypso.framework.ManejadorExcepciones | Excepcion: | HandleAbpExceptionEventHandler.HandleEvent => ManejadorExcepciones.HandleException => NLogLogger.Error | An error occurred while updating the entries. See the inner exception for details. | !
